version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./data_volume/teste-coalize:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: T3ste123
      MYSQL_DATABASE: teste
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
